# Generated by Django 2.0.7 on 2018-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(null=True),
        ),
    ]
