# Generated by Django 2.0.7 on 2018-08-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('assisted_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match')),
            ],
        ),
        migrations.CreateModel(
            name='RedCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
                ('substituted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('substitution', 'substitution'), ('assist', 'assist'), ('goal', 'goal'), ('red card', 'red card'), ('yellow card', 'yellow card')], max_length=50)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MatchTeam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='YellowCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.EventInfo')),
            ],
        ),
    ]
