# Generated by Django 2.0.7 on 2018-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('first whistle', 'first whistle'), ('last whistle', 'last whistle'), ('end of first half', 'end of first half'), ('begin of second half', 'begin of second half'), ('end of second half', 'end of second half'), ('begin of extra time', 'begin of extra time'), ('begin of extra time second half', 'begin of extra time second half'), ('end of extra time first half', 'end of extra time first half'), ('end of extra time second half', 'end of extra time second half'), ('begin of penalty shoots', 'begin of penalty shoots')], max_length=100),
        ),
    ]
