# Generated by Django 2.0.7 on 2018-10-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181026_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='area',
            field=models.CharField(default='Europe', max_length=50),
            preserve_default=False,
        ),
    ]
