# Generated by Django 2.0.7 on 2018-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_competition_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='crest_uri',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
