# Generated by Django 2.0.7 on 2018-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181101_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration',
            field=models.CharField(choices=[('regular', 'regular'), ('extra_time', 'extra_time'), ('penalty_shootout', 'penalty_shootout')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.CharField(default='group', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='matchday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='scheduled', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
