# Generated by Django 2.0.7 on 2018-10-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181028_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
