# Generated by Django 2.0.7 on 2018-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181108_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminmatch',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
