# Generated by Django 2.0.7 on 2018-11-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_teaminmatch_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.Match'),
        ),
    ]
