# Generated by Django 2.0.7 on 2018-11-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Match'),
        ),
    ]
