# Generated by Django 2.0.7 on 2018-11-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181110_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminmatch',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
    ]
