# Generated by Django 2.0.7 on 2018-11-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181110_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminmatch',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.Team'),
        ),
    ]
