# Generated by Django 2.0.7 on 2018-11-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20181110_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='match', to='app.Competition'),
        ),
        migrations.AlterField(
            model_name='teaminmatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team_in_match', to='app.Match'),
        ),
        migrations.AlterField(
            model_name='teaminmatch',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='team_in_match', to='app.Team'),
        ),
    ]
